### PR TITLE
don't use default password

### PR DESCRIPTION
**Pull request by vbatts**
https://git.fedorahosted.org/cgit/spin-kickstarts.git/commit/?id=6ba647a663f09da4ba740eb99733a39cba58d204

### CODE REVIEW

**Comment by cgwalters** [comment]
:+1: yes.  Also worth linking to https://fedorahosted.org/rel-eng/ticket/6170

**Comment by cgwalters** [comment]
...except this doesn't actually change the pre-built tarball right?

So we need to pull it from
https://fedorahosted.org/rel-eng/ticket/6170#comment:5

**Comment by lsm5** [comment]
kickstart used here pulled from fedorahosted/spin-kickstarts

**Pull request closed without merging**
